DROP TABLE SALE_ITEM;
DROP TABLE SALE;
DROP TABLE BASKET;
DROP TABLE ITEM_IMG;
DROP TABLE ITEM_OPTION;
DROP TABLE ITEM;
DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE CUSTOMER;

DROP SEQUENCE CUSTOMER_NO_SEQ;
DROP SEQUENCE BOARD_NO_SEQ;
DROP SEQUENCE REPLY_NO_SEQ;
DROP SEQUENCE ITEM_NO_SEQ;
DROP SEQUENCE ITEM_OPTION_NO_SEQ;
DROP SEQUENCE ITEM_IMG_NO_SEQ;
DROP SEQUENCE BASKET_NO_SEQ;
DROP SEQUENCE SALE_NO_SEQ;

CREATE TABLE CUSTOMER(
    CUSTOMER_NO NUMBER PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(30) UNIQUE NOT NULL,
    CUSTOMER_PWD VARCHAR2(40) NOT NULL,
    CUSTOMER_NAME VARCHAR2(40) NOT NULL,
    CUSTOMER_EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    CUSTOMER_ADDR VARCHAR2(200) NOT NULL,
    CUSTOMER_PHONE VARCHAR2(13) UNIQUE NOT NULL,
    CUSTOMER_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CUSTOMER_MOD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CUSTOMER_MONEY NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(200) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    BOARD_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_MOD_DATE DATE DEFAULT SYSDATE NOT NULL,
    BOARD_ORIGINAL_IMG VARCHAR2(60),
    BOARD_STORED_IMG VARCHAR2(260) UNIQUE,
    BOARD_IMG_SIZE NUMBER,
    BOARD_VIEW_COUNT NUMBER DEFAULT 0,
    CUSTOMER_NO NUMBER REFERENCES CUSTOMER(CUSTOMER_NO)
);

CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(1000) NOT NULL,
    REPLY_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CUSTOMER_NO NUMBER REFERENCES CUSTOMER(CUSTOMER_NO) NOT NULL,
    BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO) NOT NULL
);

CREATE TABLE ITEM(
    ITEM_NO NUMBER PRIMARY KEY,
    ITEM_NAME VARCHAR2(60) NOT NULL,
    ITEM_PRICE NUMBER NOT NULL,
    ITEM_STOCK NUMBER NOT NULL,
    ITEM_CONTENT VARCHAR2(4000),
    ITEM_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_MOD_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_VIEW_COUNT NUMBER DEFAULT 0 NOT NULL,
    ITEM_SOLD_COUNT NUMBER DEFAULT 0 NOT NULL,
    ITEM_STATE VARCHAR2(260) NOT NULL
);

CREATE TABLE ITEM_IMG(
    ITEM_IMG_NO NUMBER PRIMARY KEY,
    ITEM_ORIGINAL_IMG_NAME VARCHAR2(60) NOT NULL,
    ITEM_STORED_IMG_NAME VARCHAR2(260) NOT NULL,
    ITEM_IMG_SIZE NUMBER NOT NULL,
    ITEM_IMG_THUMBNAIL VARCHAR2(10) NOT NULL,
    ITEM_IMG_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_IMG_MOD_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_NO NUMBER NOT NULL REFERENCES ITEM(ITEM_NO)
);

CREATE TABLE ITEM_OPTION(
    ITEM_OPTION_NO NUMBER PRIMARY KEY,
    ITEM_OPTION_NAME VARCHAR2(100) NOT NULL,
    ITEM_OPTION_PRICE NUMBER NOT NULL,
    ITEM_OPTION_STOCK NUMBER NOT NULL,
	ITEM_OPTION_SOLD_COUNT NUMBER DEFAULT 0 NOT NULL,
    ITEM_OPTION_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_OPTION_MOD_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_OPTION_STATE VARCHAR2(260) DEFAULT '활성화' NOT NULL,
    ITEM_NO NUMBER NOT NULL REFERENCES ITEM(ITEM_NO)
);

CREATE TABLE BASKET(
    BASKET_NO NUMBER PRIMARY KEY,
    ITEM_NO NUMBER NOT NULL REFERENCES ITEM(ITEM_NO),
    BASKET_ITEM_VOLUME NUMBER DEFAULT 1 NOT NULL,
    BASKET_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    BASKET_MOD_DATE DATE DEFAULT SYSDATE NOT NULL,
    ITEM_OPTION_NO NUMBER NOT NULL REFERENCES ITEM_OPTION(ITEM_OPTION_NO),
    CUSTOMER_NO NUMBER NOT NULL REFERENCES CUSTOMER(CUSTOMER_NO)
);

CREATE TABLE SALE(
    SALE_NO NUMBER PRIMARY KEY,
    SALE_NAME VARCHAR2(30) NOT NULL,
    SALE_ADDR VARCHAR2(100) NOT NULL,
    SALE_PHONE VARCHAR2(13) NOT NULL,
    SALE_COMMENT VARCHAR2(100) NOT NULL,
    SALE_DATE DATE DEFAULT SYSDATE NOT NULL,
    SALE_PRICE NUMBER NOT NULL,
    SALE_STATE VARCHAR2(260) NOT NULL,
    CUSTOMER_NO NUMBER REFERENCES CUSTOMER(CUSTOMER_NO)
);

CREATE TABLE SALE_ITEM(
    SALE_NO NUMBER NOT NULL REFERENCES SALE(SALE_NO),
    ITEM_NO NUMBER NOT NULL REFERENCES ITEM(ITEM_NO),
    ITEM_NAME VARCHAR2(60) NOT NULL,
    ITEM_OPTION_NO NUMBER NOT NULL REFERENCES ITEM_OPTION(ITEM_OPTION_NO),
	ITEM_OPTION_NAME VARCHAR2(60) NOT NULL,
    SALE_ITEM_VOLUME NUMBER NOT NULL,
    PRIMARY KEY(SALE_NO, ITEM_NO, ITEM_OPTION_NO)
);

CREATE SEQUENCE CUSTOMER_NO_SEQ
INCREMENT BY 1
START WITH 10;

CREATE SEQUENCE BOARD_NO_SEQ
INCREMENT BY 1
START WITH 15;

CREATE SEQUENCE REPLY_NO_SEQ
INCREMENT BY 1
START WITH 12;

CREATE SEQUENCE ITEM_NO_SEQ
INCREMENT BY 1
START WITH 35;

CREATE SEQUENCE ITEM_OPTION_NO_SEQ
INCREMENT BY 1
START WITH 110;

CREATE SEQUENCE ITEM_IMG_NO_SEQ
INCREMENT BY 1
START WITH 110;

CREATE SEQUENCE BASKET_NO_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE SALE_NO_SEQ
INCREMENT BY 1
START WITH 1;